name: waffir
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  firebase_storage: ^11.7.4
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  get: ^4.4.6
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  fluttertoast:
  url_launcher: ^6.1.12
  get_storage: ^2.1.1
  flutter_native_splash: ^2.2.16
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.2
  image_picker: ^1.0.4
  file_picker: ^4.5.1
  google_sign_in: ^6.2.1
  dzair_data_usage: ^1.0.1
  confetti: ^0.7.0

  
flutter_native_splash:
  color: "#0B622E"
  color_dark: "#0B622E"
  image: assets\logos\splash-logo.png
  image_dark: assets\logos\splash-logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_bording/
    - assets/images/
    - assets/icons/
    - assets/images/banners/
    - assets/images/produits/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
